name: Upload to Test PyPI

on:
  workflow_dispatch:

jobs:
  test-pypi-publish:
    name: Publish To Test PyPI

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: ${{ 'testpypi' }}
      url: https://test.pypi.org/p/${{ 'name used in `pip install`' }}


    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        persist-credentials: false

    - name: Setup Python ${{ '3.x' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ '3.x' }}

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Build
      run: |
        python -m pip install build

    - name: Build Repo
      run: python -m build ${{ '.' }}

    - name: Upload to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
