name: Black

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: "./src"
      repository:
        type: string
        default: ${{ github.repository }}

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}

      - name: Run Black
        uses: psf/black@stable
        with:
            options: "--check --verbose --color"
            src: ${{ inputs.path }}
