name: Build Distribution

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: "./src"

      python-version:
        type: string
        default: "3.x"

      repository:
        type: string
        default: ${{ github.repository }}


      artifact-name:
        type: string
        default: "python-package-distributions"


jobs:
  build-distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          persist-credentials: false

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Build
        run: |
          python -m pip install build

      - name: Build Repo
        run: python -m build

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ inputs.artifact-name }}
          path: dist/

