name: MyPy

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      setup-path:
        type: string
        default: "."
      mypy-config:
        type: string
        default: "mypy.ini"


jobs:
  mypy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    name: MyPy ${{ matrix.python-version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Tools (Wheel, Setuptools, MyPy)
        run: |
          python -m pip install wheel setuptools mypy

      - name: Build & Install Repo
        run: |
          python -m pip install ${{ inputs.setup-path }}

      - name: Run MyPy
        run: |
          mypy --config-file ${{ inputs.mypy-config }} --namespace-packages -p ${{ inputs.package }}
