name: Publish to Test PyPI

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: "./src"

      python-version:
        type: string
        default: "3.x"

      repository:
        type: string
        default: ${{ github.repository }}

      artifact-name:
        type: string
        default: "python-package-distributions"

      package-name:
        type: string
        required: true

jobs:
  build-dist:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/build/build-distribution.yaml@main
    with:
      path: ${{ inputs.path }}
      python-version: ${{ inputs.python-version }}
      repository: ${{ inputs.repository }}
      artifact-name: ${{ inputs.artifact-name }}

  publish-dist:
    needs: build-dist
    uses: MAK-Relic-Tool/Workflows/.github/workflows/build/publish-dist-to-testpypi.yaml
    with:
      package-name: ${{ inputs.package-name }}
      artifact-name: ${{ inputs.artifact-name }}