name: Publish to PyPI

on:
  workflow_call:
    inputs:
      python-version:
        type: string

      path:
        required: true
        type: string

    secrets:
      pypi-token:
        required: true

    defaults:
      python-version: "3.x"

jobs:
  pypi:
    runs-on: ubuntu-latest

    name: Publish to PyPI

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Tools (Build)
        run: |
          python -m pip install build

      - name: Build Repo
        run: python -m build ${{ inputs.setup-path }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi-token }}
