name: Publish to Test PyPI

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true

      artifact-name:
        type: string
        default: "python-package-distributions"

jobs:
  pypi:
    runs-on: ubuntu-latest

    name: Publish to Test PyPI

    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.package-name }}x

    permissions:
      id-token: write

    steps:
    - name: Download Distribution
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: dist/

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: "https://test.pypi.org/legacy/"
