name: Publish to PyPI

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true

      artifact-name:
        type: string
        default: "python-package-distributions"

      publish-env:
        type: string
        default: "pypi"

jobs:
  pypi:
    runs-on: ubuntu-latest

    name: Publish to PyPI

    environment:
      name: ${{ inputs.publish-env }}
      url: https://pypi.org/p/${{ inputs.package-name }}

    permissions:
      id-token: write

    steps:
    - name: Download Distribution
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.artifact-name }}
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
