name: Publish to PyPI

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.x"
        
      setup-path:
        type: string
        default: "."

      package-name:
        type: string
        required: true

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ inputs.package-name }}x
    permissions:
      id-token: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}x

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Tools (Build)
      run: |
        python -m pip install build

    - name: Build package
      run: python -m build ${{ inputs.setup-path }}

    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
