name: Pylint

on:
  workflow_call:

    inputs:
      python-version:
        required: true
        type: string

      path:
        required: true
        type: string

    jobs:
      pylint:
        runs-on: ubuntu-latest

        name: Pylint ${{ inputs.python-version }}

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Setup Python ${{ inputs.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ inputs.python-version }}

          - name: Upgrade Pip
            run: |
              python -m pip install --upgrade pip

          - name: Install Tools (Pylint)
            run: |
              python -m pip install pylint

          - name: Run Pylint
            run: |
              pylint ${{ inputs.path }}
